name: for learn

on:
    workflow_dispatch:

concurrency:
    group: group-1
    cancel-in-progress: false
jobs:
    job-1:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                A: [1, 2, 3, 4, 5, 6, 7, 8, 9]
                B: [a, b, c, d, e]
                include:
                    - A: 10
                      B: x
                exclude:
                    - A: 1
                      B: e
            fail-fast: false

        steps:
            - name: summe th valeu
              run: echo ${{matrix.A}} + ${{matrix.B}}
