name: for learn

on:
    workflow_dispatch:

concurrency:
    group: group-1
    cancel-in-progress: false
jobs:
    job-1:
        runs-on: ubuntu-latest
        outputs:
            A: ${{steps.s11.outputs.A}}
            B: ${{steps.s11.outputs.B}}
        strategy:
            matrix:
                A: [1, 2, 3, 4, 5, 6, 7, 8, 9]
                B: [a, b, c, d, e]
                include:
                    - A: 10
                      B: x
                exclude:
                    - A: 1
                      B: e
            fail-fast: false

        steps:
            - name: summe th valeu
              id: s11
              if: matrix.B == 'e' && matrix.A == 2
              run: |
                  B=${{matrix.B}} >> $GITHUB_OUTPUT
                  A=${{matrix.A}} >> $GITHUB_OUTPUT

    job-2:
        runs-on: ubuntu-latest
        needs: [job-1]
        steps:
            - name: show the resualt
              if: needs.job-1.outputs.A == 2 && needs.job-1.outputs.B == 'e'
              run: echo ${{needs.job-1.outputs.B}}
