name: workflow_1
on:
    workflow_call:
        inputs:
            A:
                required: true
                type: string
            B:
                required: false
                type: number
        secrets:
            SA:
                required: false

jobs:
    run_echo:
        name: call an other workflow
        uses: ./.github/workflows/test.yml
