name: workflow_1
on:
    workflow_call:
        inputs:
            A:
                required: true
                type: string
            B:
                required: false
                type: number
        secrets:
            SA:
                required: true

jobs:
    run_echo:
        runs-on: ubuntu-latest
        steps:
            - name: call an other workflow
              uses: ./.github/workflows/test.yml@master
