name: workflow_2
on:
    workflow_dispatch:
jobs:
    call-wf1:
        name: test
        uses: ./.github/workflows/wf.yml
        with:
            A: "hi there"
            B: 125
        secrets:
            SA: A
