name: workflow_2

on:
    workflow_dispatch:

jobs:
    call-wf1:
        runs-on: ubuntu-latest
        environment: Keys
        env:
            A: ${{secrets.AWS_KEY}}
        steps:
            - name: call
              uses: ./.github/workflows/wf.yml@master
              with:
                  A: "hi there"
                  B: 125
                  secrets: A
